---
- hosts: all
  vars:
    do_not_install_packages_after_build: true
  roles:
    - debian-packaging
  tasks:
    - name: Run the installation script
      become: yes
      command: >
          ansible-playbook -i inventories/uc-engine uc-engine.yml
          --extra-vars wazo_distribution=wazo-dev-buster
          --extra-vars wazo_distribution_upgrade=wazo-dev-buster
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-ansible"

    - name: create acceptance config
      blockinfile:
        create: yes
        path: ~/.wazo-acceptance/config.yml
        block: |
          debug:
            global: True

            acceptance: True
            linphone: True
            xivo_test_helpers: True
          instances:
            default:
              wazo_host: "{{ ansible_docker0.ipv4.address }}"

    - name: Setup acceptance tests
      shell: "tox -e setup"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-acceptance"

    - name: Run acceptance tests
      shell: "tox -e behave -- features/daily"
      args:
        chdir: "{{ zuul.project.src_dir }}/../wazo-acceptance"
